title: Thanic Samin
description: PhD Student in Mathematics at Indiana University
show_downloads: false
google_analytics:
theme: jekyll-theme-midnight
favicon: /assets/images/favicon.ico

remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one